modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="astral_disturbance"
version="0.0.1"
displayName="Astral Disturbance"
displayURL="https://github.com/TerrifiedTaco/Astral-Disturbance"
credits="lodestone is great"
authors="TerrifiedTaco, MrC08"

[[dependencies.astral_disturbance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.astral_disturbance]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.astral_disturbance]]
    modId="lodestone"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

